version: 2

aliases:
  - &restore-cache
    restore_cache:
      key: dependency-cache-{{ checksum "package.json" }}
  - &install
    run:
      name: Install dependencies
      command: yarn install
  - &build
    run:
      name: Build
      command: yarn build
  - &run-tests
    run:
      name: Test
      command: yarn test

tests-template: &tests-template
  working_directory: ~/sarina
  steps:
    - checkout
    - *restore-cache
    - *install
    - *build
    - *run-tests

jobs:
  test_node_13:
    <<: *tests-template
    docker:
      - image: circleci/node:13
  test_node_12:
    <<: *tests-template
    docker:
      - image: circleci/node:12

  test_node_10:
    <<: *tests-template
    docker:
      - image: circleci/node:10
  tagging:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - run: VERSION=$(my-binary --version) && ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  build-and-test:
    jobs:
      - test_node_13
      - test_node_12
      - test_node_10
      - tagging
